[[redirects]]
  from = "/render-en/ssr/one"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/render-en/ssr/two"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/render-en/ssr/three"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/en/render-en/ssr/one"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/en/render-en/ssr/two"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/en/render-en/ssr/three"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/nl/render-nl/ssr/one"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/nl/render-nl/ssr/two"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/nl/render-nl/ssr/three"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/fr/render-fr/ssr/one"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/fr/render-fr/ssr/two"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/fr/render-fr/ssr/three"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/render/ssg"
  to = "/.netlify/functions/___netlify-odb-handler"
  status = 200